namespace PerfConverter;

public enum DLFilterFlag : uint
{
    PERF_DLFILTER_FLAG_BRANCH = 1 << 0,
    PERF_DLFILTER_FLAG_CALL = 1 << 1,
    PERF_DLFILTER_FLAG_RETURN = 1 << 2,
    PERF_DLFILTER_FLAG_CONDITIONAL = 1 << 3,
    PERF_DLFILTER_FLAG_SYSCALLRET = 1 << 4,
    PERF_DLFILTER_FLAG_ASYNC = 1 << 5,
    PERF_DLFILTER_FLAG_INTERRUPT = 1 << 6,
    PERF_DLFILTER_FLAG_TX_ABORT = 1 << 7,
    PERF_DLFILTER_FLAG_TRACE_BEGIN = 1 << 8,
    PERF_DLFILTER_FLAG_TRACE_END = 1 << 9,
    PERF_DLFILTER_FLAG_IN_TX = 1 << 10,
    PERF_DLFILTER_FLAG_VMENTRY = 1 << 11,
    PERF_DLFILTER_FLAG_VMEXIT = 1 << 12,
};
